# Generated by Django 2.2.14 on 2020-11-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='estudiante',
        ),
        migrations.AddField(
            model_name='clase',
            name='created',
            field=models.DateTimeField(auto_created=True, auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='clase',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
