# Generated by Django 2.2.14 on 2020-11-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0006_auto_20201120_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
